project:
  type: website

website:
  title: "MSci Romanzini-Bezerra Slides"
  site-url: https://bezerragrasi.github.io/slides/
  description: "Public facing homepage for MSci Romanzini-Bezerra's slides collection"
